project_name: horcrux

builds:
  - binary: horcrux
    goos:
      - windows
      - darwin
      - linux

    goarch:
      - amd64
      - 386
      - arm
      - arm64

release:
  github:
    owner: corvus-ch
    name: horcrux

archives:
  - format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE
      - README.md
      - CONTRIBUTING.md

brews:
  - tap:
      owner: corvus-ch
      name: homebrew-tools

    homepage: https://github.com/corvus-ch/horcrux
    description: A helper for preparing backups of data worth protecting

nfpms:
  - homepage: https://github.com/corvus-ch/horcrux
    description: A helper for preparing backups of data worth protecting
    maintainer: Christian Häusler <haeusler.christian@mac.com>
    license: MIT

    formats:
      - deb
      - rpm

    suggests:
      - gpg
      - paperkey

    bindir: /usr/bin
