language: go

go:
  - "1.10"

branches:
  only:
    - master

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y --no-install-recommends libgfshare-bin

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - make install

script:
  - make test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
